[package]
name = "adriftdev_pid"
version = "1.0.0"
authors = ["Joshua Tracey <joshua.tracey@connect.qut.edu.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]